//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public long Id { get; set; }
        public string HolidayName { get; set; }
        public long HolidayType { get; set; }
        public System.DateTime HolidayDate { get; set; }
    }
}
